### ISSUE TITLE
Frontend: Dashboard

### ISSUE THREAD

**Issue by arjun1237** [arjun1237/arthashastra-expense-manager#6]
- [x] Total Income - (Sum of all credit)

- [x] Total Expenses - (Sum of all debits)

- [x] Balance - (Credit - Debit)

- [x] Transaction - (List of last five recent transactions)

- [x] Enter Transaction

    Title - (Min 3 Characters)
    Type - (Credit/Debit - Radio)
    Amount

- [x] On submission the details will be stored along with the timestamp

**Comment by aravindsakthivel** [comment]
Dashboard completed
