### ISSUE TITLE
frontend: Login

### ISSUE THREAD

**Issue by arjun1237** [arjun1237/arthashastra-expense-manager#8]
- [x] Login with Email & Password

- [x] If the email doesn’t exists show a message “Account doesn’t exists”

- [x] If the Email & Password doesn’t match show a message “Wrong Password”

- [x] This messages must be shown below the login button

**Comment by arjun1237** [comment]
for login:
i will need these from body while logging in:
-> username
-> password

**Comment by aravindsakthivel** [comment]
![Screenshot from 2020-10-10 18-57-24](https://user-images.githubusercontent.com/59511858/95671433-e80b3700-0bb4-11eb-98f0-2b925247d67a.png)

Is this fine or do you need a different color

**Comment by arjun1237** [comment]
the login design is looking good.

- [x] make the background white.

- [x] the navbar logo... get it from font awesome - check for good logos

- [x] make the navbar and button color same - have shades of same color - dont use too many colors if its not relevant

**Comment by aravindsakthivel** [comment]
![Screenshot from 2020-10-11 11-27-29](https://user-images.githubusercontent.com/59511858/95671478-5cde7100-0bb5-11eb-9b2a-946cee296b16.png)
Is this fine

**Comment by arjun1237** [comment]
this is looking better.

- [x] change the logo

- [x] reduce the navbar height

**Comment by aravindsakthivel** [comment]
![Screenshot from 2020-10-11 12-38-49](https://user-images.githubusercontent.com/59511858/95672488-ca42cf80-0bbe-11eb-9460-7703d5fc0198.png)
![Screenshot from 2020-10-11 12-38-53](https://user-images.githubusercontent.com/59511858/95672491-cca52980-0bbe-11eb-85cf-4850c422b289.png)
![Screenshot from 2020-10-11 12-40-25](https://user-images.githubusercontent.com/59511858/95672507-f6f6e700-0bbe-11eb-9aa6-4da4817cc6fe.png)
is this fine

**Comment by arjun1237** [comment]
its looking really good in login ... but make the logo white in navbar
also shrink navbar even more and show me

**Comment by arjun1237** [comment]
- [x] also make the email and mobile input  in separate lines

**Comment by aravindsakthivel** [comment]
![Screenshot from 2020-10-11 12-55-57](https://user-images.githubusercontent.com/59511858/95672767-23136780-0bc1-11eb-8340-1b6fe84d5f32.png)

**Comment by arjun1237** [comment]
looking perfect... on to dashboard now
